apiVersion: v2
type: application
name: trilium
description: |-
  Build your personal knowledge base with Trilium Notes. A hierarchical note taking application with focus on building large personal knowledge bases.
home: https://github.com/TriliumNext/helm-charts
icon: https://raw.githubusercontent.com/TriliumNext/Trilium/main/apps/client/src/assets/icon.png
# Managed by release-please.
version: 1.3.0
# renovate: image=triliumnext/trilium
appVersion: v0.104.0
kubeVersion: ">=1.28.0-0"
dependencies:
  - name: common
    repository: https://bjw-s-labs.github.io/helm-charts
    version: 5.0.1
keywords:
  - trilium
  - notes
  - wiki
  - knowledge-base
  - note-taking
  - self-hosted
annotations:
  category: Notes
maintainers:
  - name: triliumnext
    url: https://github.com/TriliumNext
  - name: perfectra1n
    email: jon@jonfuller.io
    url: https://perf3ct.tech
sources:
  - https://github.com/TriliumNext/helm-charts
  - https://github.com/TriliumNext/Trilium
